services:
  evolution_postgres:
    container_name: evolution_postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution
      POSTGRES_DB: evolution
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data

  evolution_redis:
    container_name: evolution_redis
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - evolution_redis_data:/data

  evolution_api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    depends_on:
      - evolution_postgres
      - evolution_redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
  evolution_postgres_data:
  evolution_redis_data:
